CREATE TABLE CURSOS (
    ID_CURSO BIGINT NOT NULL DEFAULT nextval('SEQ_CURSOS'),
    DT_CRIADO_EM TIMESTAMP NOT NULL DEFAULT current_timestamp,
	ID_CRIADO_POR BIGINT NOT NULL,
	DT_ATUALIZADO_EM TIMESTAMP NOT NULL,
	ID_ATUALIZADO_POR BIGINT NOT NULL,
    NM_CURSO VARCHAR(255) NOT NULL,
    VL_MENSAL DECIMAL(10, 2) NOT NULL,
    FL_ATIVA BOOLEAN NOT NULL,

    CONSTRAINT PK_CURSOS PRIMARY KEY(ID_CURSO)
);

CREATE TABLE ALUNOS (
    ID_ALUNO BIGINT NOT NULL DEFAULT nextval('SEQ_ALUNOS'),
    DT_CRIADO_EM TIMESTAMP NOT NULL DEFAULT current_timestamp,
	ID_CRIADO_POR BIGINT NOT NULL,
	DT_ATUALIZADO_EM TIMESTAMP NOT NULL,
	ID_ATUALIZADO_POR BIGINT NOT NULL,
    NM_ALUNO VARCHAR(255) NOT NULL,
    TP_CONTATO INTEGER NOT NULL,
    DS_CONTATO VARCHAR(255) NOT NULL,
    NR_DIA_PAGAMENTO INTEGER NOT NULL,
    FL_ATIVA BOOLEAN NOT NULL,

    CONSTRAINT PK_ALUNOS PRIMARY KEY(ID_ALUNO)
);

CREATE TABLE TURMAS (
    ID_TURMA BIGINT NOT NULL DEFAULT nextval('SEQ_TURMAS'),
    DT_CRIADO_EM TIMESTAMP NOT NULL DEFAULT current_timestamp,
	ID_CRIADO_POR BIGINT NOT NULL,
	DT_ATUALIZADO_EM TIMESTAMP NOT NULL,
	ID_ATUALIZADO_POR BIGINT NOT NULL,
    TP_DIA_SEMANA INTEGER NOT NULL,
    HR_AULA TIME NOT NULL,
    FL_ATIVA BOOLEAN NOT NULL,
    ID_CURSO BIGINT NOT NULL,

    CONSTRAINT PK_TURMAS PRIMARY KEY(ID_TURMA),
    CONSTRAINT FK_TURMAS_CURSOS FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO) ON DELETE CASCADE
);

CREATE TABLE AULAS (
    ID_AULA BIGINT NOT NULL DEFAULT nextval('SEQ_AULAS'),
    DT_CRIADO_EM TIMESTAMP NOT NULL DEFAULT current_timestamp,
	ID_CRIADO_POR BIGINT NOT NULL,
	DT_ATUALIZADO_EM TIMESTAMP NOT NULL,
	ID_ATUALIZADO_POR BIGINT NOT NULL,
    DT_AULA TIMESTAMP NOT NULL,
    ID_TURMA BIGINT,

    CONSTRAINT PK_AULAS PRIMARY KEY(ID_AULA),
    CONSTRAINT FK_AULAS_TURMAS FOREIGN KEY (ID_TURMA) REFERENCES TURMAS(ID_TURMA) ON DELETE SET NULL
);

CREATE TABLE PAGAMENTOS (
    ID_PAGAMENTO BIGINT NOT NULL DEFAULT nextval('SEQ_PAGAMENTOS'),
    DT_CRIADO_EM TIMESTAMP NOT NULL DEFAULT current_timestamp,
	ID_CRIADO_POR BIGINT NOT NULL,
	DT_ATUALIZADO_EM TIMESTAMP NOT NULL,
	ID_ATUALIZADO_POR BIGINT NOT NULL,
    DT_REFERENCIA DATE NOT NULL,
    VL_PAGO DECIMAL(10, 2) NOT NULL,
    DT_EFETIVACAO DATE,
    TP_PAGAMENTO INTEGER NOT NULL,
    FL_PENDENTE BOOLEAN NOT NULL,
    ID_ALUNO BIGINT NOT NULL,
    ID_TURMA BIGINT,

    CONSTRAINT PK_PAGAMENTOS PRIMARY KEY(ID_PAGAMENTO),
    CONSTRAINT FK_PAGAMENTOS_ALUNOS FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO) ON DELETE CASCADE,
    CONSTRAINT FK_PAGAMENTOS_TURMAS FOREIGN KEY (ID_TURMA) REFERENCES TURMAS(ID_TURMA) ON DELETE SET NULL
);

CREATE TABLE TURMAS_ALUNOS (
    ID_TURMA BIGINT NOT NULL,
    ID_ALUNO BIGINT NOT NULL,

    CONSTRAINT PK_TURMAS_ALUNOS PRIMARY KEY (ID_TURMA, ID_ALUNO),
    CONSTRAINT FK_TURMASALUNOS_TURMAS FOREIGN KEY (ID_TURMA) REFERENCES TURMAS(ID_TURMA) ON DELETE CASCADE,
    CONSTRAINT FK_TURMASALUNOS_ALUNOS FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO) ON DELETE CASCADE
);

CREATE TABLE PRESENCAS (
	ID_PRESENCA BIGINT NOT NULL DEFAULT nextval('SEQ_PRESENCAS'),
	DT_CRIADO_EM TIMESTAMP NOT NULL DEFAULT current_timestamp,
	ID_CRIADO_POR BIGINT NOT NULL,
	DT_ATUALIZADO_EM TIMESTAMP NOT NULL,
	ID_ATUALIZADO_POR BIGINT NOT NULL,
    ID_AULA BIGINT NOT NULL,
    ID_ALUNO BIGINT NOT NULL,
    FL_PRESENTE BOOLEAN NOT NULL,

    CONSTRAINT PK_PRESENCAS PRIMARY KEY (ID_PRESENCA),
    CONSTRAINT FK_PRESENCAS_AULAS FOREIGN KEY (ID_AULA) REFERENCES AULAS(ID_AULA) ON DELETE CASCADE,
    CONSTRAINT FK_PRESENCAS_ALUNOS FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO) ON DELETE CASCADE
);