CREATE SEQUENCE SEQ_CURSOS START 1;
CREATE SEQUENCE SEQ_ALUNOS START 1;
CREATE SEQUENCE SEQ_TURMAS START 1;
CREATE SEQUENCE SEQ_AULAS START 1;
CREATE SEQUENCE SEQ_PAGAMENTOS START 1;
CREATE SEQUENCE SEQ_PRESENCAS START 1;