DROP TABLE IF EXISTS PRESENCAS CASCADE;
DROP TABLE IF EXISTS TURMAS_ALUNOS CASCADE;
DROP TABLE IF EXISTS PAGAMENTOS CASCADE;
DROP TABLE IF EXISTS AULAS CASCADE;
DROP TABLE IF EXISTS TURMAS CASCADE;
DROP TABLE IF EXISTS ALUNOS CASCADE;
DROP TABLE IF EXISTS CURSOS CASCADE;

DROP SEQUENCE IF EXISTS SEQ_AULAS;
DROP SEQUENCE IF EXISTS SEQ_PAGAMENTOS;
DROP SEQUENCE IF EXISTS SEQ_TURMAS;
DROP SEQUENCE IF EXISTS SEQ_ALUNOS;
DROP SEQUENCE IF EXISTS SEQ_CURSOS;
DROP SEQUENCE IF EXISTS SEQ_PRESENCAS;

DROP VIEW IF EXISTS VW_RELATORIO_PAGAMENTOS;