//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atelie.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atelie.Core.Resources.GlobalMessages", typeof(GlobalMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abril.
        /// </summary>
        public static string Abril {
            get {
                return ResourceManager.GetString("Abril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ações.
        /// </summary>
        public static string Acoes {
            get {
                return ResourceManager.GetString("Acoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar Aluno.
        /// </summary>
        public static string AdicionarAluno {
            get {
                return ResourceManager.GetString("AdicionarAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agosto.
        /// </summary>
        public static string Agosto {
            get {
                return ResourceManager.GetString("Agosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aguardando pagamento.
        /// </summary>
        public static string Aguardando {
            get {
                return ResourceManager.GetString("Aguardando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O registro {0} {1} foi alterado com sucesso!.
        /// </summary>
        public static string AlteradoComSucesso {
            get {
                return ResourceManager.GetString("AlteradoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aluno.
        /// </summary>
        public static string Aluno {
            get {
                return ResourceManager.GetString("Aluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alunos.
        /// </summary>
        public static string Alunos {
            get {
                return ResourceManager.GetString("Alunos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alunos Matriculados.
        /// </summary>
        public static string AlunosMatriculados {
            get {
                return ResourceManager.GetString("AlunosMatriculados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ano.
        /// </summary>
        public static string Ano {
            get {
                return ResourceManager.GetString("Ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Até.
        /// </summary>
        public static string Ate {
            get {
                return ResourceManager.GetString("Ate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativo?.
        /// </summary>
        public static string AtivoPergunta {
            get {
                return ResourceManager.GetString("AtivoPergunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativos.
        /// </summary>
        public static string Ativos {
            get {
                return ResourceManager.GetString("Ativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aula.
        /// </summary>
        public static string Aula {
            get {
                return ResourceManager.GetString("Aula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aviso do Sistema.
        /// </summary>
        public static string AvisoDoSistema {
            get {
                return ResourceManager.GetString("AvisoDoSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bem-vindo ao Ateliê Osana Muciaccia!.
        /// </summary>
        public static string BemVindoAoAtelie {
            get {
                return ResourceManager.GetString("BemVindoAoAtelie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é obrigatório..
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Celular.
        /// </summary>
        public static string Celular {
            get {
                return ResourceManager.GetString("Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirme para prosseguir a ação!.
        /// </summary>
        public static string ConfirmacaoSistema {
            get {
                return ResourceManager.GetString("ConfirmacaoSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmar.
        /// </summary>
        public static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Crédito.
        /// </summary>
        public static string Credito {
            get {
                return ResourceManager.GetString("Credito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Curso.
        /// </summary>
        public static string Curso {
            get {
                return ResourceManager.GetString("Curso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cursos.
        /// </summary>
        public static string Cursos {
            get {
                return ResourceManager.GetString("Cursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data da Aula.
        /// </summary>
        public static string DataDaAula {
            get {
                return ResourceManager.GetString("DataDaAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Efetivação.
        /// </summary>
        public static string DataEfetivacao {
            get {
                return ResourceManager.GetString("DataEfetivacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data da aula não pode ser no passado..
        /// </summary>
        public static string DataNoPassado {
            get {
                return ResourceManager.GetString("DataNoPassado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Referência.
        /// </summary>
        public static string DataReferencia {
            get {
                return ResourceManager.GetString("DataReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a De.
        /// </summary>
        public static string De {
            get {
                return ResourceManager.GetString("De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Débito.
        /// </summary>
        public static string Debito {
            get {
                return ResourceManager.GetString("Debito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Descrição do Contato.
        /// </summary>
        public static string DescricaoContato {
            get {
                return ResourceManager.GetString("DescricaoContato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deslogar.
        /// </summary>
        public static string Deslogar {
            get {
                return ResourceManager.GetString("Deslogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dezembro.
        /// </summary>
        public static string Dezembro {
            get {
                return ResourceManager.GetString("Dezembro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dia Da Semana.
        /// </summary>
        public static string DiaDaSemana {
            get {
                return ResourceManager.GetString("DiaDaSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dia de Pagamento.
        /// </summary>
        public static string DiaDePagamento {
            get {
                return ResourceManager.GetString("DiaDePagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Dia de Pagamento deve receber um valor entre 1 e 31..
        /// </summary>
        public static string DiaPagamentoInvalido {
            get {
                return ResourceManager.GetString("DiaPagamentoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dia de Pagamento Preferencial.
        /// </summary>
        public static string DiaPagamentoPreferencial {
            get {
                return ResourceManager.GetString("DiaPagamentoPreferencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dinheiro.
        /// </summary>
        public static string Dinheiro {
            get {
                return ResourceManager.GetString("Dinheiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Domingo.
        /// </summary>
        public static string Domingo {
            get {
                return ResourceManager.GetString("Domingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Efetivação.
        /// </summary>
        public static string Efetivacao {
            get {
                return ResourceManager.GetString("Efetivacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formato do e-mail fornecido é inválido..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrar.
        /// </summary>
        public static string Entrar {
            get {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um aluno com esse mesmo nome..
        /// </summary>
        public static string ErroAlunoComNomeExistente {
            get {
                return ResourceManager.GetString("ErroAlunoComNomeExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir um aluno com histórico de pagamentos pendentes..
        /// </summary>
        public static string ErroAlunoComPendencias {
            get {
                return ResourceManager.GetString("ErroAlunoComPendencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este aluno {0}  já possui um registro de presença para esta aula..
        /// </summary>
        public static string ErroAlunoComPresenca {
            get {
                return ResourceManager.GetString("ErroAlunoComPresenca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir um aluno que está matriculado em turmas..
        /// </summary>
        public static string ErroAlunoMatriculado {
            get {
                return ResourceManager.GetString("ErroAlunoMatriculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir uma aula que já possui registros de presença..
        /// </summary>
        public static string ErroAulaComPresenca {
            get {
                return ResourceManager.GetString("ErroAulaComPresenca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para salvar uma aula, deve conter pelo menos um aluno na lista de presença..
        /// </summary>
        public static string ErroAulaSemPresenca {
            get {
                return ResourceManager.GetString("ErroAulaSemPresenca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uma aula deve ser associada a uma turma existente..
        /// </summary>
        public static string ErroAulaSemTurma {
            get {
                return ResourceManager.GetString("ErroAulaSemTurma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir um curso que tenha turmas relacionadas a ele..
        /// </summary>
        public static string ErroCursoComTurmas {
            get {
                return ResourceManager.GetString("ErroCursoComTurmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível concluir essa ação pois o curso está inativo..
        /// </summary>
        public static string ErroCursoInativo {
            get {
                return ResourceManager.GetString("ErroCursoInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O curso não pode ser desativado pois possui turmas ativas: {0}..
        /// </summary>
        public static string ErroDesativarCurso {
            get {
                return ResourceManager.GetString("ErroDesativarCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível excluir um pagamento que já foi efetivado..
        /// </summary>
        public static string ErroExclusaoPagamentoEfetivado {
            get {
                return ResourceManager.GetString("ErroExclusaoPagamentoEfetivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro inesperado, caso persista, entre em contato com o técnico responsável.
        ///
        ///{0}.
        /// </summary>
        public static string ErroInesperado {
            get {
                return ResourceManager.GetString("ErroInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um pagamento deve ser associado a um aluno existente..
        /// </summary>
        public static string ErroPagamentoSemAluno {
            get {
                return ResourceManager.GetString("ErroPagamentoSemAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um registro de presença deve ser associado a um aluno..
        /// </summary>
        public static string ErroPresencaSemAluno {
            get {
                return ResourceManager.GetString("ErroPresencaSemAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um registro de presença deve ser associado a uma aula..
        /// </summary>
        public static string ErroPresencaSemAula {
            get {
                return ResourceManager.GetString("ErroPresencaSemAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreram um ou mais erros de validação..
        /// </summary>
        public static string ErrosValidacao {
            get {
                return ResourceManager.GetString("ErrosValidacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A turma não pode ser inativa caso possua alunos nela..
        /// </summary>
        public static string ErroTurmaInativaComAluno {
            get {
                return ResourceManager.GetString("ErroTurmaInativaComAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma turma neste mesmo dia e com horário entre 30min antes ou depois do horário escolhido..
        /// </summary>
        public static string ErroTurmaMesmoHorario {
            get {
                return ResourceManager.GetString("ErroTurmaMesmoHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro de validação..
        /// </summary>
        public static string ErroValidacao {
            get {
                return ResourceManager.GetString("ErroValidacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O registro {0} {1} foi excluido com sucesso!.
        /// </summary>
        public static string ExcluidoComSucesso {
            get {
                return ResourceManager.GetString("ExcluidoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exportar.
        /// </summary>
        public static string Exportar {
            get {
                return ResourceManager.GetString("Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exportar Relatório.
        /// </summary>
        public static string ExportarRelatorio {
            get {
                return ResourceManager.GetString("ExportarRelatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Faça seu login!.
        /// </summary>
        public static string FacaLogin {
            get {
                return ResourceManager.GetString("FacaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Faltas.
        /// </summary>
        public static string Faltas {
            get {
                return ResourceManager.GetString("Faltas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        public static string Fechar {
            get {
                return ResourceManager.GetString("Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fevereiro.
        /// </summary>
        public static string Fevereiro {
            get {
                return ResourceManager.GetString("Fevereiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filtrar.
        /// </summary>
        public static string Filtrar {
            get {
                return ResourceManager.GetString("Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerir Alunos  da Turma.
        /// </summary>
        public static string GerirAlunos {
            get {
                return ResourceManager.GetString("GerirAlunos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Horário.
        /// </summary>
        public static string Horario {
            get {
                return ResourceManager.GetString("Horario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inativos.
        /// </summary>
        public static string Inativos {
            get {
                return ResourceManager.GetString("Inativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Aluno.
        /// </summary>
        public static string IncluirAluno {
            get {
                return ResourceManager.GetString("IncluirAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Aula.
        /// </summary>
        public static string IncluirAula {
            get {
                return ResourceManager.GetString("IncluirAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Curso.
        /// </summary>
        public static string IncluirCurso {
            get {
                return ResourceManager.GetString("IncluirCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Pagamento.
        /// </summary>
        public static string IncluirPagamento {
            get {
                return ResourceManager.GetString("IncluirPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir Turma.
        /// </summary>
        public static string IncluirTurma {
            get {
                return ResourceManager.GetString("IncluirTurma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Janeiro.
        /// </summary>
        public static string Janeiro {
            get {
                return ResourceManager.GetString("Janeiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Julho.
        /// </summary>
        public static string Julho {
            get {
                return ResourceManager.GetString("Julho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Junho.
        /// </summary>
        public static string Junho {
            get {
                return ResourceManager.GetString("Junho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limpar.
        /// </summary>
        public static string Limpar {
            get {
                return ResourceManager.GetString("Limpar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lista de Presença.
        /// </summary>
        public static string ListaPresenca {
            get {
                return ResourceManager.GetString("ListaPresenca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A carregar dados....
        /// </summary>
        public static string LoadingCarregarDados {
            get {
                return ResourceManager.GetString("LoadingCarregarDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Maio.
        /// </summary>
        public static string Maio {
            get {
                return ResourceManager.GetString("Maio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Março.
        /// </summary>
        public static string Marco {
            get {
                return ResourceManager.GetString("Marco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mês das Presenças.
        /// </summary>
        public static string MesDePresencaFiltro {
            get {
                return ResourceManager.GetString("MesDePresencaFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mês de Referência.
        /// </summary>
        public static string MesDeReferencia {
            get {
                return ResourceManager.GetString("MesDeReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um ou mais erros de regra de negócio..
        /// </summary>
        public static string MultiplosErrors {
            get {
                return ResourceManager.GetString("MultiplosErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não Informado.
        /// </summary>
        public static string NaoInformado {
            get {
                return ResourceManager.GetString("NaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não Pendentes.
        /// </summary>
        public static string NaoPendentes {
            get {
                return ResourceManager.GetString("NaoPendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um(a) {0} cadastrado(a) com este nome..
        /// </summary>
        public static string NomeExistente {
            get {
                return ResourceManager.GetString("NomeExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novembro.
        /// </summary>
        public static string Novembro {
            get {
                return ResourceManager.GetString("Novembro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Outubro.
        /// </summary>
        public static string Outubro {
            get {
                return ResourceManager.GetString("Outubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento.
        /// </summary>
        public static string Pagamento {
            get {
                return ResourceManager.GetString("Pagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este aluno já possui um pagamento registrado para este mês de referência..
        /// </summary>
        public static string PagamentoDuplicadoMes {
            get {
                return ResourceManager.GetString("PagamentoDuplicadoMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um pagamento efetivado deve ter uma data de efetivação..
        /// </summary>
        public static string PagamentoEfetivadoDataEfetivacao {
            get {
                return ResourceManager.GetString("PagamentoEfetivadoDataEfetivacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um pagamento efetivado deve ter um tipo de pagamento válido (PIX, Dinheiro, etc.)..
        /// </summary>
        public static string PagamentoEfetivadoTipoPagamentoValido {
            get {
                return ResourceManager.GetString("PagamentoEfetivadoTipoPagamentoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um pagamento pendente não pode ter uma data de efetivação..
        /// </summary>
        public static string PagamentoPendenteEfetivacao {
            get {
                return ResourceManager.GetString("PagamentoPendenteEfetivacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um pagamento pendente deve ter o tipo &apos;Aguardando Pagamento&apos;..
        /// </summary>
        public static string PagamentoPendenteTipoAdequado {
            get {
                return ResourceManager.GetString("PagamentoPendenteTipoAdequado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamentos Pendentes/Pagos.
        /// </summary>
        public static string PagamentosGrafico {
            get {
                return ResourceManager.GetString("PagamentosGrafico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagos.
        /// </summary>
        public static string Pagos {
            get {
                return ResourceManager.GetString("Pagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pendente?.
        /// </summary>
        public static string PendentePergunta {
            get {
                return ResourceManager.GetString("PendentePergunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pendentes.
        /// </summary>
        public static string Pendentes {
            get {
                return ResourceManager.GetString("Pendentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pix.
        /// </summary>
        public static string Pix {
            get {
                return ResourceManager.GetString("Pix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Presença.
        /// </summary>
        public static string Presenca {
            get {
                return ResourceManager.GetString("Presenca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Presença Mensal.
        /// </summary>
        public static string PresencaMensal {
            get {
                return ResourceManager.GetString("PresencaMensal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Presenças.
        /// </summary>
        public static string Presencas {
            get {
                return ResourceManager.GetString("Presencas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Presente?.
        /// </summary>
        public static string PresentePergunta {
            get {
                return ResourceManager.GetString("PresentePergunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quarta-Feira.
        /// </summary>
        public static string Quarta {
            get {
                return ResourceManager.GetString("Quarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quinta-Feira.
        /// </summary>
        public static string Quinta {
            get {
                return ResourceManager.GetString("Quinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Referência.
        /// </summary>
        public static string Referencia {
            get {
                return ResourceManager.GetString("Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O(a) {0} {1} foi registrado(a) com sucesso!.
        /// </summary>
        public static string RegistradoComSucesso {
            get {
                return ResourceManager.GetString("RegistradoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sábado.
        /// </summary>
        public static string Sabado {
            get {
                return ResourceManager.GetString("Sabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        public static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Segunda-Feira.
        /// </summary>
        public static string Segunda {
            get {
                return ResourceManager.GetString("Segunda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione.
        /// </summary>
        public static string Selecione {
            get {
                return ResourceManager.GetString("Selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Setembro.
        /// </summary>
        public static string Setembro {
            get {
                return ResourceManager.GetString("Setembro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sexta-Feira.
        /// </summary>
        public static string Sexta {
            get {
                return ResourceManager.GetString("Sexta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        public static string Telefone {
            get {
                return ResourceManager.GetString("Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Terça-Feira.
        /// </summary>
        public static string Terca {
            get {
                return ResourceManager.GetString("Terca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo do Contato.
        /// </summary>
        public static string TipoContato {
            get {
                return ResourceManager.GetString("TipoContato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo Pagamento.
        /// </summary>
        public static string TipoPagamento {
            get {
                return ResourceManager.GetString("TipoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total de Alunos.
        /// </summary>
        public static string TotalAlunos {
            get {
                return ResourceManager.GetString("TotalAlunos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turma.
        /// </summary>
        public static string Turma {
            get {
                return ResourceManager.GetString("Turma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turma Ativa?.
        /// </summary>
        public static string TurmaAtivaPergunta {
            get {
                return ResourceManager.GetString("TurmaAtivaPergunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Referente à Turma.
        /// </summary>
        public static string TurmaReferente {
            get {
                return ResourceManager.GetString("TurmaReferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário ou senha inválidos..
        /// </summary>
        public static string UsuarioSenhaInvalido {
            get {
                return ResourceManager.GetString("UsuarioSenhaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor Mensal.
        /// </summary>
        public static string ValorMensal {
            get {
                return ResourceManager.GetString("ValorMensal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor do pagamento deve ser maior que zero..
        /// </summary>
        public static string ValorPagamentoInvalido {
            get {
                return ResourceManager.GetString("ValorPagamentoInvalido", resourceCulture);
            }
        }
    }
}
